[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
include = ["mlindex*"]
exclude = ["mlindex.dataset_generation*", "mlindex.comparisons*", "mlindex.characterization*"]

[tool.setuptools.package-data]
mlindex = ["model_metadata.json", "models/*/data/hkl_ref_*.npy"]

[project]
name = "mlindex"
version = "0.1.0"
authors = [{name = "David Mittan-Moreau", email = "dwmoreau@lbl.gov"}]
description = "A data driven approach to powder diffraction indexing"
keywords = ["powder diffraction", "diffraction", "crystallography", "indexing", "machine learning"]
readme = "README.md"
requires-python = ">=3.9"
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
]
license = "MIT"
license-files = ["LICEN[CS]E*"]

dependencies = [
    "gemmi",
    "matplotlib",
    "numpy",
    "numba",
    "onnxruntime",
    "pandas",
    "scikit-learn",
    "scipy",
]

[project.optional-dependencies]
mpi = ["mpi4py"]
dataset_generation = ["pyarrow", "openpyxl", "tqdm"]
training = ["pyarrow", "openpyxl", "skl2onnx", "keras", "torch", "torchvision"]

[project.scripts]
"mlindex.run" = "mlindex.command_line.run:main"
"mlindex.run_analytical" = "mlindex.command_line.run_analytical:main"
"mlindex.download_models" = "mlindex.command_line.download_models:main"

[project.urls]
Homepage = "https://github.com/dwmoreau/MLI"
Issues = "https://github.com/dwmoreau/MLI/issues"
