"""The benchmark's condition set: the noise, contamination and sparsity each pattern is measured
under, defined once and read by everything that needs it.

A *condition bundle* is one named point in the grid. Every source crystal is simulated under every
bundle, so a "pattern-condition" -- one crystal under one condition -- is the unit every metric is
computed over. `bundle_tag` is the only implementation of the naming rule: a generation run, a
consolidator and a submit script all obtain a tag by asking this module for it rather than
rebuilding it, because two bundles that collide on a tag share an output directory and one
`manifest.json`, and the second silently overwrites the first.

The error law is Gaussian throughout, with two axes: *severity*, the multiplier, which scales the
intercept and the slope of sigma(q2) together; and *shape*, the intercept alone, which raises the
error at low q2 relative to high and which a multiplier cannot reach. Robustness to a different
error *model* -- heavier tails, a systematic 2-theta zero shift -- is untested rather than passed.

The control is deliberately not zero error. With no measurement error the residual denominator
vanishes and M20 diverges arithmetically, which makes every residual-denominator merit unusable on
exactly the bundle meant to prove nothing upstream is broken.
"""

import hashlib
import json


# Prefixes every tag. Its job is to keep this condition set's output directories from colliding
# with another pass's: an unprefixed `error1_cont1_drop6` is generated by more than one condition
# table, and two bundles sharing a directory share one manifest. Change it whenever a change to
# CONDITIONS below would let a tag mean something it did not mean before.
TAG_PREFIX = 'b1'

# The nominal sigma(q2) intercept scale. 1.0 is the repository's own value, which
# `ErrorAdder.q2_sigma_params` resolves from `EntryHelpers.get_peak_generation_info`.
NOMINAL_INTERCEPT_SCALE = 1.0

# Recorded on every entry row so a bundle's provenance is readable from the data, not from here.
ERROR_LAW = 'gaussian'

# The default rank-draw exponent for a second phase's lines: 1 picks uniformly among the partner's
# eligible lines, 2 weights towards low q2, which is roughly where a real second phase shows.
NOMINAL_SECOND_PHASE_BIAS = 2.0


class Condition:
    """One condition bundle: a named point in the grid, and the tag it generates under."""

    def __init__(self, key, label, description, axis, error_multiplier, n_contaminants,
                 intercept_scale=NOMINAL_INTERCEPT_SCALE, n_dropout=0, second_phase_lines=0,
                 second_phase_bias=NOMINAL_SECOND_PHASE_BIAS, is_hard=False):
        self.key = key
        self.label = label
        self.description = description
        self.axis = axis
        self.error_multiplier = float(error_multiplier)
        self.n_contaminants = int(n_contaminants)
        self.intercept_scale = float(intercept_scale)
        self.n_dropout = int(n_dropout)
        self.second_phase_lines = int(second_phase_lines)
        self.second_phase_bias = float(second_phase_bias)
        self.is_hard = bool(is_hard)

    @property
    def tag(self):
        return bundle_tag(self)

    def __repr__(self):
        return f'<Condition {self.key} {self.tag}>'


def bundle_tag(condition):
    """The one implementation of the tag rule.

    Accepts a Condition or anything carrying the same attribute names -- an argparse namespace
    does, which is what lets a run assembled from command-line flags tag itself.

    Every axis that is not at its default has to appear, or two bundles collide on their output
    directory. Defaults are omitted so a tag stays readable.
    """
    error_multiplier = float(getattr(condition, 'error_multiplier'))
    tag = (f'{TAG_PREFIX}_error{error_multiplier:g}'
           f'_cont{int(getattr(condition, "n_contaminants")):d}')
    intercept_scale = float(getattr(condition, 'intercept_scale', NOMINAL_INTERCEPT_SCALE))
    if intercept_scale != NOMINAL_INTERCEPT_SCALE:
        tag += f'_icept{intercept_scale:g}'
    n_dropout = int(getattr(condition, 'n_dropout', 0))
    if n_dropout:
        tag += f'_drop{n_dropout:d}'
    second_phase_lines = int(getattr(condition, 'second_phase_lines', 0))
    if second_phase_lines:
        tag += f'_phase{second_phase_lines:d}'
        second_phase_bias = float(getattr(condition, 'second_phase_bias',
                                          NOMINAL_SECOND_PHASE_BIAS))
        if second_phase_bias != NOMINAL_SECOND_PHASE_BIAS:
            tag += f'_pbias{second_phase_bias:g}'
    return tag


CONDITIONS = (
    Condition(
        key='control', label='B0', axis='control',
        description='Near-noise-free ceiling. Proves nothing upstream is broken. Not zero error: '
                    'M20 is ill-conditioned there',
        error_multiplier=0.5, n_contaminants=0,
        ),
    Condition(
        key='nominal', label='B1', axis='reference',
        description='The reference condition every other bundle is contrasted against',
        error_multiplier=1, n_contaminants=0,
        ),
    Condition(
        key='noisy', label='B2', axis='error_severity',
        description='Twice the nominal sigma(q2). Scales intercept and slope together',
        error_multiplier=2, n_contaminants=0, is_hard=True,
        ),
    Condition(
        key='error_shape', label='B3', axis='error_shape',
        description='Nominal severity, four times the sigma(q2) y-intercept. Raises sigma at low '
                    'q2 relative to high q2, which a multiplier cannot do',
        error_multiplier=1, n_contaminants=0, intercept_scale=4.0,
        ),
    Condition(
        key='contaminated1', label='B4', axis='contamination',
        description='One independently placed contaminant line',
        error_multiplier=1, n_contaminants=1,
        ),
    Condition(
        key='contaminated2', label='B5', axis='contamination',
        description='Two independently placed contaminant lines',
        error_multiplier=1, n_contaminants=2, is_hard=True,
        ),
    Condition(
        key='sparse2', label='B6', axis='sparsity',
        description='Two interior peaks dropped and backfilled from beyond the 20th. Nested: '
                    'these holes are a subset of sparse4 and sparse6',
        error_multiplier=1, n_contaminants=1, n_dropout=2,
        ),
    Condition(
        key='sparse4', label='B7', axis='sparsity',
        description='Four interior peaks dropped. Nested: a superset of sparse2, a subset of '
                    'sparse6',
        error_multiplier=1, n_contaminants=1, n_dropout=4, is_hard=True,
        ),
    Condition(
        key='sparse6', label='B8', axis='sparsity',
        description='Six interior peaks dropped. Nested: a superset of sparse4',
        error_multiplier=1, n_contaminants=1, n_dropout=6, is_hard=True,
        ),
    Condition(
        key='second_phase', label='B9', axis='second_phase',
        description='Three lines from a real partner cell drawn from the database. Correlated, '
                    'unlike independently placed contaminants, which is what makes them hard to '
                    'reject',
        error_multiplier=1, n_contaminants=0, second_phase_lines=3, is_hard=True,
        ),
    )

BY_KEY = {condition.key: condition for condition in CONDITIONS}
BY_TAG = {condition.tag: condition for condition in CONDITIONS}
BUNDLE_LABELS = {condition.tag: condition.label for condition in CONDITIONS}

# The sparsity rungs, ascending, because the nesting is implemented by drawing the holes once at
# the largest rung and taking prefixes -- which is what "prefix" means here. The nesting lives in
# the peak-list preparation, not in this table.
SPARSITY_LADDER = tuple(sorted(
    condition.n_dropout for condition in CONDITIONS if condition.axis == 'sparsity'))
MAX_NESTED_DROPOUT = max(SPARSITY_LADDER) if SPARSITY_LADDER else 0

# The severe end of each axis. Membership is a per-condition flag rather than a rule over axes, so
# adding a mild bundle to an axis that already has a severe one cannot enlarge the hard population
# by accident.
HARD_BUNDLES = tuple(condition.tag for condition in CONDITIONS if condition.is_hard)


def tags():
    return tuple(condition.tag for condition in CONDITIONS)


def condition_row(condition):
    """One flat record per bundle, for the condition table shipped as an artefact."""
    return {
        'key': condition.key,
        'label': condition.label,
        'tag': condition.tag,
        'axis': condition.axis,
        'error_law': ERROR_LAW,
        'error_multiplier': condition.error_multiplier,
        'intercept_scale': condition.intercept_scale,
        'n_contaminants': condition.n_contaminants,
        'n_dropout': condition.n_dropout,
        'second_phase_lines': condition.second_phase_lines,
        'second_phase_bias': condition.second_phase_bias,
        'is_hard': condition.is_hard,
        'description': condition.description,
        }


def condition_set_digest():
    """A digest of the whole table, written into every manifest.

    Two arms are only paired if this matches. A description is part of the digest deliberately:
    it is cheap to keep stable, and a table that has been edited at all is worth re-reading before
    its numbers are compared with another run's.
    """
    payload = json.dumps([condition_row(condition) for condition in CONDITIONS],
                         sort_keys=True, separators=(',', ':'))
    return hashlib.sha256(payload.encode('utf-8')).hexdigest()
